apache/db-jdo-site

src/main/asciidoc/field_types.adoc

The icons that are currently used on http://db.apache.org/jdo/field_types.html
are not very clear (IMHO). A clearer version is made available using this pull request, which then looks like the ones on the equivalent DN docs page, http://www.datanucleus.org:15080/products/accessplatform_5_2/jdo/mapping.html#_java_math_types

change icon type to be clearer

---

.github/workflows/deploy-site.yml
README.md

Adds a GitHub workflow to auto-deploy the site if any of its sources
have changed and the build was successful.
The action is only run if
- the correct branches are pushed (currently only `master`)
AND
- at least one file in the correct paths was modified (currently
`src/main/asciidoc/**` and `src/main/template/**`).
If the build was successful, the action copies the build results from
'`target/site/*` to `docs/` and creates a new commit with all changed
files in `docs/`. This commit is automatically pushed to the branch that
triggered the GitHub action. The new commit is attributed to the author
of the latest commit on that branch.
Removed the note to move the build results into the `docs/` folder when
creating a commit from the README as this is now done automatically.

Add GitHub workflow to auto-deploy site

---

CONTRIBUTING.md
README.md
src/main/asciidoc/get-involved.adoc
src/main/asciidoc/source-code.adoc

This PR updates the user information on how to build the site and contribute to the project. It updates the README, adds a CONTRIBUTING page, and updates the "Get Involved" page on the website.
<details><summary><b>Rework README</b></summary>
<br>
Restructures the readme to make it easier to read and find the necessary
information.
Drops the instructions on how to use git. If the potential contributor
does not know how to use it, this readme is not the place for them to
learn it.
Removes the entry on committing the generated site artifacts. This
should be done separately to keep the pull requests clean.
Adds links to GitHub resources explaining the basic GitHub workflow.
</details>
<details><summary><b>Add CONTRIBUTING page</b></summary>
<br>
This page will be linked to whenever a new PR …

Update contribution guidelines

---

.github/workflows/deploy-site.yml

Replaces the external action with bare-bones logic accomplishing the
same goal. This was done to avoid the usage of external GitHub actions.
This new logic is most likely more brittle than the functionality
provided by the external action. It will fail if the author data of the
HEAD commit can not be read and will also always push the new commit to
the currently checked out branch, i.e. the branch that triggered the
action. The workflow is configured to currently only run on the master
branch, but this behavior should still be kept in mind in case of future
changes to the setup.

Implement rudimentary push logic for deploy action

---

.asf.yaml
.asf.yaml.publish
.github/workflows/deploy-site.yml
.htaccess

Adjusts the site deployment job to instead deploy the site to a separate branch. This has the advantage that the build artifacts no longer have to be kept as part of the master branch. Instead, they are pushed to the orphan branch `publish`.
The separate branch `publish` only contains the site build artifacts and the site configuration files (`.asf.yaml`). All these resources are located directly in the root directory. The site branch will be completely overwritten when a new build is deployed, so only the latest build artifacts will be stored.
Moves the site publishing configuration to the separate file `.asf.yaml.publish`. This file is renamed to `.asf.yaml` as part of the creation of the deploy commit. This separates the site deployment configuration from the rest of the configuration …

Move site to separate branch

---

.asf.yaml.publish
.github/workflows/deploy-site.yml
.github/workflows/recreate-site-branch.yml
.htaccess

Adds the necessary configuration to host the website in the `content` directory. Adjusts the deploy workflow match the new layout and to preserver the site branch history. Also introduces a recovery workflow to recreate a stable base state for the site branch in case it ever gets deleted or corrupted. This recovery is necessary as the new deploy action can't function with an existing site branch that is in the expected state.
While this solution is less elegant than I would have liked, adjusting the deploy action to also handle a missing or corrupted site branch would have required a lot of additional work and would have most likely increased the size of the workflow considerably, thereby making it harder to understand.
The results of the new build action can be observed in my fork. I …

Adjust deploy workflow to preserve history

---

src/main/asciidoc/specifications.adoc

This PR fix the links for the specification PDFs to point to the GitHub repository instead of the SVN repository.

Remove svn references for specification PDFs

---

.asf.yaml

This PR adjusts some of the GitHub repo settings that are accessible through the `.asf.yaml` file as specified in https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#git.asf.yamlfeatures-GitHubsettings.
In particular, this PR sets up branch protection for the `publish` branch, ensuring that it can't be deleted. This was done to avoid accidental deletions of the branch which could potentially break the website deployment.

Adjust GitHub conf after site migration

---

.github/workflows/deploy-site.yml
.github/workflows/recreate-site-branch.yml

Cleans up the existing GitHub actions. Each change is described in more details in the corresponding commit message. I would suggest looking at the changes commit by commit instead of looking at the entire diff all at once.

Clean up deploy actions

---

.github/workflows/deploy-site.yml

Adjusts the deploy action to only try to commit and push if there are
any staged changes. This avoids the action "failing" if there is nothing
to commit.
This explicitly fixes the use-case of re-triggering an already successful action run. When there is nothing to commit, the "Publish Results" step is skipped, which is also shown in the action log. This makes it immediately apparent that the job ran successfully but did not deploy any changes to the site branch (see [example run](https://github.com/tobous/db-jdo-site/runs/1864040848)).

Only try to publish results if there are any changes

---

.asf.yaml

Adds specific notification settings in the asf.yaml configuration.
Diverts messages regarding new commits being pushed to the 'jdo-commits'
mailing list to avoid clogging up 'jdo-dev'. The notifications for
pull-requests and issues still go to 'jdo-dev'.
Adds the preexisting jira linking options to the configurations. With
the current configuration, the label 'pull-request-available' and a link
to the pull-request/issue is automatically added to any Jira ticket that
is referenced in the pull-request/issue name. See wiki for more details.
The current configuration can be viewed [here](https://gitbox.apache.org/schemes.cgi?db-jdo-site). With this change, the settings for the site repo will match the [notification settings for the main repo](https://gitbox.apache.org/schemes.cgi?db-jdo).

Set notification settings in .asf.yaml

---

src/main/asciidoc/get-involved.adoc

Mentions the capability to automatically referencing a pull request in a
JIRA ticket by including a reference to the ticket in the pull request
title in the "Get Involved" section.
The wording was chosen carefully not to imply that this would actually
link the state of the two. As far as I can tell, merging the pull
request will not have any influence on the state of the referenced
ticket. If this is actually the case, the wording should be adjusted to
reflect the behavior.
This functionality is described in the [`.asf.yaml` wiki](https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#Git.asf.yamlfeatures-Jiranotificationoptions).

Mention automatic JIRA linking as part of the "Get Involved" page

---

src/main/asciidoc/index.adoc
src/main/template/document.html.erb

Adjusts the website to use the 150x150 version of the JDO logo instead
of smaller ones. Sets the scaling manually to keep the previous size
when using the larger image.
Adjusts the image size of the header icon to better fit the bar and
create an even spacing with the default layout.

Use icons with highest resolution available for website

---

.github/workflows/deploy-site.yml

Simplifies the deploy workflow branch rule by switching to specifying
which branches to run on.
I previously thought that 'branch' and 'path' rules were compared with
an OR operator. From my new tests, this does not seem to be the case.
Instead, they are compared with the AND operator, allowing for this
simplified configuration.

Simplify workflow branch rule

---

.github/workflows/deploy-site.yml
.github/workflows/recreate-site-branch.yml
pom.xml

- Moved the execution of copy-resources from compile to prepare-package phase.
- Replaced 'mvn clean compile' by 'mvn clean package' in the github workflows deploy-site and recreate-site-branch

Move copy-resources from compile to prepare-package lifecycle phase

---

.github/workflows/deploy-site.yml
pom.xml
src/main/template/document.html.erb

Here are the updates of the pom.xml:
- Added Apache License
- Added Apache parent pom
- Changed groupId to org.apache.jdo (same as db-jdo)
- Changed artifactId to jdo-site
- Changed version to 3.2-SNAPSHOT (same as db-jdo)
- Changed name to Apache JDO Site
- Added description
- Fixed url
- Added organization
- Added scm block with gitbox url
- Updated dependency of asciidoctor maven plugin to most recent version 
- Removed commented out line
Please note the update to version 2 of asciidoctor maven plugin requires some configuration changes.
Also when converting glossary.adoc asciidoctor prints three info messages, which are false positive:
INFO: possible invalid reference: application-identity
I also updated the copyright notice in the template to include 2021

JDO-789: Cleanup jdo-site pom

---

.asf.yaml

Adjusts the branch protection to use the previous name for the required
action. As this change will only apply after it was merged into master,
the name of the required action will be changed separately.

Adjust branch protection to use previous name

---

.github/workflows/build-site.yml

This reverts commit e5def6b2a20602562f346b14eb5d3f01d2b8a735.
This fix was necessary to allow us to merge pull requests. Now that the
configuration has been updated, the nicer action name should be
restored.

Revert "Fix branch protection"

---

.asf.yaml

Remove required GitHub actions to allow directly pushing to 'master'.
Also prevent accidental desyncs when directly pushing to 'master'
through GitBox.

Remove required GitHub actions

---

.asf.yaml

Disables the branch protection for the publish branch so that it can be force-pushed with a clean build.

Disable branch protection for publish branch
